# Server port?? ??
server:
  port: 8761

# Eureka ?? ??
spring:d
  application:
    name: discoveryservice
# ????? Eureka? MSA ???? ???? ???? ???? ???? true? ???? ??.
# Eureka ?? ???? true? ? ?? ?????? ??? ???? false ??? ???.
eureka:
  client:
    register-with-eureka: false
    #Eureka ????? ?????? ??? ????? ??? ???? ???? ??, true ??? ??? ?? ?? ???? ??
    fetch-registry: false
