spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/connected
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        format_sql: true
        user_sql_cooments: true

    hibernate:
      ddl-auto: create

#  profiles를 추가하여 secret을 추가하면 application-sercret.yml에 작성된 설정값을 읽을 수 있다
  profiles:
    active: local
    include: secret

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

      hiberante:
        SQL: debug

    boardexample:
      myboard: info