server:
  # ?? ??? 0?? ?? ?? Random?? ???? ??? ????
  port: 0
spring:
  application:
    name: user-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    #?? ??? 0?? ???? Random Port? ???? ?? Instance ??? 0? ??? ???? ? ?? Instance? ????? ??? ??? ???? ?? ?????.
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}